core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('projects/', include('projects.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('account/', views.account, name='account'),
    path('logout/', views.logout_user, name='logout'),
    path('', views.profiles, name='profiles'),

    path('profile-info/', views.profile_info, name='profile_info'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('profile-overview/<str:pk>/', views.profile_overview, name='profile_overview'),
    path('profile/<str:username>/', views.profile, name='profile'),

    path('load_cities/', views.load_cities, name='load_cities'),

    path('skill-list/', views.skill_list, name='skill_list'),
    path('load_skills/', views.load_skills, name='load_skills'),
    path('add-skill/', views.add_skill, name='add_skill'),
    path('delete-skill/<str:pk>/', views.delete_skill, name='delete_skill'),

    path('social-list/', views.social_list, name='social_list'),
    path('add-social/', views.add_social, name='add_social'),
    path('delete-social/<str:pk>/', views.delete_social, name='delete_social'),
]

templates/includes/footer.html
<footer class="bg-dark text-white py-3 mt-5">
    <div class="container text-center">
        <p>&copy; 2025 DevHub. All rights reserved.</p>
    </div>
</footer>

templates/includes/messages.html
{% if messages %}
    <div class="d-flex justify-content-center w-100 fixed-top" style="z-index: 1050; margin-top: 30px;">
        {% for message in messages %}
            <div class="alert dark-alert alert-{{ message.tags }} mt-2 alert-dismissible fade show text-center" role="alert"
                style="max-width: 300px;">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/includes/navbar.html
<nav class="navbar bg-dark border-bottom border-body sticky-top navbar-expand-lg" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="/">DevHub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item radius-md bg-dimmed me-2">
                    <a href="{% url 'users:profiles' %}" class="nav-link" aria-current="page">
                        <i class="fa-solid fa-users"></i> Developers
                    </a>
                </li>
                <li class="nav-item radius-md bg-dimmed me-2">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-briefcase"></i> Projects
                    </a>
                </li>
                
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown radius-md bg-dimmed">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            <i class="fas fa-user"></i> Profile
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'users:account' %}" class="dropdown-item">
                                    <i class="fa-solid fa-user me-2"></i> Account
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <button
                                    data-bs-toggle="modal"
                                    data-bs-target="#modal"
                                    hx-get="{% url 'users:logout' %}"
                                    hx-target="#dialog"
                                    class="dropdown-item text-danger">
                                    <i class="fa-solid fa-sign-out-alt me-2"></i> Logout
                                </button>
                            </li>
                            
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item radius-md bg-dimmed me-2">
                        <a href="{% url 'account_login' %}" class="nav-link">
                            <i class="fa-solid fa-sign-in"></i> Sign In / Sign Up
                        </a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'users:profiles' %}">
                <input name="search_query" class="form-control me-2 radius-md" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light radius-md d-flex align-items-center" type="submit">
                    <i class="fas fa-search me-2"></i> Search
                </button>
            </form>
        </div>
    </div>
</nav>

templates/includes/pagination.html
{% if queryset.has_other_pages %}

<nav>
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link {% if not queryset.has_previous %}disabled{% endif %}" href="
                {% if search_query %}
                    ?search_query={{search_query}}&page=1
                {% else %}
                    ?page=1
                {% endif %}
            ">
                &#10094;&#10094;
            </a>
        </li>

        {% if queryset.has_previous %}
            <li class="page-item">
                <a class="page-link" href="
                    {% if search_query %}
                        ?search_query={{ search_query }}&page={{ queryset.previous_page_number }}
                    {% else %}
                        ?page={{ queryset.previous_page_number }}
                    {% endif %}
                ">
                    &#10094;
                </a>
            </li>
        {% endif %}

        {% for page in custom_range %}
            <li class="page-item">
                <a class="page-link {% if page == queryset.number %}active{% endif %}" href="
                    {% if search_query %}
                        ?search_query={{search_query}}&page={{page}}
                    {% else %}
                        ?page={{page}}
                    {% endif %}
                ">
                    {{ page }}
                </a>
            </li>
        {% endfor %}
        
        {% if queryset.has_next %}
            <li class="page-item">
                <a class="page-link" href="
                    {% if search_query %}
                        ?search_query={{ search_query }}&page={{ queryset.next_page_number }}
                    {% else %}
                        ?page={{ queryset.next_page_number }}
                    {% endif %}
                ">
                    &#10095;
                </a>
            </li>
        {% endif %}     

        <li class="page-item">
            <a class="page-link {% if not queryset.has_next %}disabled{% endif %}" href="
                {% if search_query %}
                    ?search_query={{search_query}}&page={{ pg.num_pages }}
                {% else %}
                    ?page={{ pg.num_pages }}
                {% endif %}
            ">
                &#10095;&#10095;
            </a>
        </li>
    </ul>
</nav>

{% endif %}