core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('projects/', include('projects.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('project/', views.project, name='project'),
    path('project-list/', views.project_list, name='project_list'),

    path('add-project/', views.add_project, name='add_project'),
    path('edit-project/<str:pk>/', views.edit_project, name='edit_project'),
    path('delete-project/<str:pk>/', views.delete_project, name='delete_project'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('account/', views.account, name='account'),
    path('logout/', views.logout_user, name='logout'),
    path('', views.profiles, name='profiles'),

    path('profile-info/', views.profile_info, name='profile_info'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('profile-overview/<str:pk>/', views.profile_overview, name='profile_overview'),
    path('profile/<str:username>/', views.profile, name='profile'),

    path('load_cities/', views.load_cities, name='load_cities'),

    path('skill-list/', views.skill_list, name='skill_list'),
    path('load_skills/', views.load_skills, name='load_skills'),
    path('add-skill/', views.add_skill, name='add_skill'),
    path('delete-skill/<str:pk>/', views.delete_skill, name='delete_skill'),

    path('social-list/', views.social_list, name='social_list'),
    path('add-social/', views.add_social, name='add_social'),
    path('delete-social/<str:pk>/', views.delete_social, name='delete_social'),
]

users/models.py
from uuid import uuid4
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from utils.validators import IMAGE_EXTENSIONS, size_validator
from cities_light.models import Country, City


def upload_to(instance, filename):
    return f'profiles/{instance.user.username}/{filename}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    display_name = models.CharField(max_length=100, null=True, blank=True)
    bio = models.CharField(max_length=150, null=True, blank=True)
    
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    
    about_info = models.TextField(null=True, blank=True)

    image = models.ImageField(
        default='default/default_pfp.png',
        upload_to=upload_to,
        validators=[
            FileExtensionValidator(allowed_extensions=IMAGE_EXTENSIONS),
            size_validator
        ]
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id = models.UUIDField(default=uuid4, unique=True, editable=False, primary_key=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.user.username
    
    def get_name(self):
        return self.display_name if self.display_name else self.user.username
    
    @property
    def get_username(self):
        return self.user.username
    
    def get_location(self):
        data = [
            self.city.name if self.city else None,
            self.country.name if self.country else None
        ]
        return ', '.join(filter(None, data))
    
    @property
    def get_skills(self):
        return self.skills.all()
    
    @property
    def get_socials(self):
        return self.socials.all()
    
    @property
    def get_projects(self):
        return self.projects.all()
    
    @property
    def get_bio(self):
        return self.bio if self.bio else ''


class SkillCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    id = models.UUIDField(default=uuid4, unique=True, editable=False, primary_key=True)

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=100, unique=True)
    category = models.ForeignKey(SkillCategory, on_delete=models.CASCADE, related_name='skills')

    id = models.UUIDField(default=uuid4, unique=True, editable=False, primary_key=True)

    def __str__(self):
        return self.name
    

class ProfileSkill(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='skills')
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)

    id = models.UUIDField(default=uuid4, unique=True, editable=False, primary_key=True)

    class Meta:
        unique_together = ('profile', 'skill')

    def __str__(self):
        return self.profile.user.username
    
    @property
    def name(self):
        return self.skill.name
    

class Social(models.Model):
    name = models.CharField(max_length=50, unique=True)
    id = models.UUIDField(default=uuid4, unique=True, editable=False, primary_key=True)

    def __str__(self):
        return self.name
    

class ProfileSocial(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='socials')
    social = models.ForeignKey(Social, on_delete=models.CASCADE)
    url = models.URLField(max_length=100, null=True)

    id = models.UUIDField(default=uuid4, unique=True, editable=False, primary_key=True)

    class Meta:
        unique_together = ('profile', 'social')

    def __str__(self):
        return self.profile.get_username
    
    @property
    def name(self):
        return self.social.name

users/forms.py
from django import forms
from allauth.account.forms import LoginForm, SignupForm
from django.forms import inlineformset_factory
from .models import *
from cities_light.models import Country, City


class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'form-control',
            })


class CustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'form-control',
            })


class ProfileForm(forms.ModelForm):
    country = forms.ModelChoiceField(
        queryset=Country.objects.all(),
        required=False,
        widget=forms.Select(attrs={
            'hx-get': '/load_cities/',
            'hx-target': '#id_city',
        })
    )
    city = forms.ModelChoiceField(
        queryset=City.objects.none(),
        required=False  
    )

    class Meta:
        model = Profile
        fields = ['display_name', 'bio', 'country', 'city', 'about_info', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        if 'country' in self.data and self.data.get('country'):
            country_id = int(self.data.get('country'))
            self.fields['city'].queryset = City.objects.filter(country_id=country_id)
        elif self.instance and self.instance.pk and self.instance.country:
            self.fields['city'].queryset = City.objects.filter(country=self.instance.country)
            self.initial['city'] = self.instance.city


class ProfileSkillForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=SkillCategory.objects.all(),
        required=True,
        widget=forms.Select(
            attrs={
                'hx-get': '/load_skills/',
                'hx-target': '#id_skill',
                'class': 'form-control'
            }
        )
    )

    skill = forms.ModelChoiceField(
        queryset=Skill.objects.none(),
        required=True,
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = ProfileSkill
        fields = ['category', 'skill']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'category' in self.data and self.data.get('category'):
            category_id = self.data.get('category')
            self.fields['skill'].queryset = Skill.objects.filter(category_id=category_id)


class ProfileSocialForm(forms.ModelForm):
    class Meta:
        model = ProfileSocial
        fields = ['social', 'url']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'form-control',
            })

users/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.postgres.search import SearchQuery, SearchVector, SearchRank, SearchHeadline
from django.contrib.postgres.aggregates import StringAgg
from django.db.models import Value, CharField
from django.db.models.functions import Coalesce
from django.http import HttpResponse
from django.urls import reverse
from .forms import *
from .models import *
from cities_light.models import City
from utils.pagination import pagination
from utils.htmx_response import htmx_http_response


@login_required(login_url='account_login')
def account(request):
    profile = request.user.profile
    context = {
        'profile': profile,
        'page': 'account'
    }

    return render(request, 'users/account.html', context)


@login_required(login_url='account_login')
def profile_info(request):
    profile = request.user.profile
    context = {
        'profile': profile
    }
    return render(request, 'users/partials/profile_info.html', context)


@login_required(login_url='account_login')
def edit_profile(request):
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()

            message = {
                'text': 'Profile was updated',
                'type': 'success'
            }

            return htmx_http_response(204, message, event='profileInfoChanged')

    form = ProfileForm(instance=profile)

    context = {
        'form': form,
    }

    return render(request, 'users/edit_profile.html', context)


def load_cities(request):
    country_id = request.GET.get('country')

    if not country_id:
        return HttpResponse("<option value=''>No available cities for this region</option>")

    cities = City.objects.filter(country_id=country_id)

    if not cities.exists():
        return HttpResponse("<option value=''>No available cities for this region</option>")

    context = {
        'queryset': cities,
    }

    return render(request, 'users/obj_options.html', context)


def load_skills(request):
    category_id = request.GET.get('category')

    if not category_id:
        return HttpResponse("<option value=''>No available skills for this category</option>")
    
    skills = Skill.objects.filter(category_id=category_id)

    if not skills.exists():
        return HttpResponse("<option value=''>No available skills for this category</option>")
    
    context = {
        'queryset': skills,
    }

    return render(request, 'users/obj_options.html', context)


@login_required(login_url='account_login')
def skill_list(request):
    profile = request.user.profile
    skills = profile.get_skills

    context = {
        'skills': skills,
    }

    return render(request, 'users/partials/skill_list.html', context)


@login_required(login_url='account_login')
def add_skill(request):
    if request.method == 'POST':
        form = ProfileSkillForm(request.POST)
        if form.is_valid():
            skill = form.cleaned_data.get('skill')
            profile = request.user.profile

            obj, created = ProfileSkill.objects.get_or_create(profile=profile, skill=skill)

            message = {
                'text': obj.name + ' was added' if created else 'is already added',
                'type': 'success' if created else 'danger'
            }

            return htmx_http_response(204, message, event='skillListChanged')

    form = ProfileSkillForm()

    context = {
        'form': form,
        'obj_name': 'Skill',
        'url': request.path
    }

    return render(request, 'users/obj_form.html', context)


@login_required(login_url='account_login')
def delete_skill(request, pk):
    skill = get_object_or_404(ProfileSkill, id=pk)

    if request.method == 'POST':
        skill.delete()

        message = {
            'text': f'{skill.name} was removed',
            'type': 'danger'
        }

        return htmx_http_response(204, message, event='skillListChanged')

    context = {
        'url': reverse('users:delete_skill', args=[skill.id]),
        'obj_name': 'Skill',
        'obj_name_value': skill.name,
    }

    return render(request, 'obj/obj_delete.html', context)


@login_required(login_url='account_login')
def social_list(request):
    profile = request.user.profile
    socials = profile.get_socials

    context = {
        'socials': socials,
    }

    return render(request, 'users/partials/social_list.html', context)


@login_required(login_url='account_login')
def add_social(request):
    if request.method == 'POST':
        form = ProfileSocialForm(request.POST)
        if form.is_valid():
            social = form.cleaned_data.get('social')
            url = form.cleaned_data.get('url')
            profile = request.user.profile

            obj, created = ProfileSocial.objects.get_or_create(profile=profile, social=social, url=url)

            message = {
                'text': obj.name.capitalize() + ' link was added' if created else 'is already added',
                'type': 'success' if created else 'danger'
            }

            return htmx_http_response(204, message, event='socialListChanged')

    form = ProfileSocialForm()

    context = {
        'form': form,
        'obj_name': 'Social',
        'url': request.path,
    }

    return render(request, 'users/obj_form.html', context)


@login_required(login_url='account_login')
def delete_social(request, pk):
    social = get_object_or_404(ProfileSocial, id=pk)

    if request.method == 'POST':
        social.delete()

        message = {
            'text': f'{social.name.capitalize()} was removed',
            'type': 'danger'
        }

        return htmx_http_response(204, message, event='socialListChanged')
    
    context = {
        'url': reverse('users:delete_social', args=[social.id]),
        'obj_name': 'Social',
        'obj_name_value': social.name,
    }

    return render(request, 'obj/obj_delete.html', context)


@login_required(login_url='account_login')
def logout_user(request):
    if request.method == 'POST':
        logout(request)
        messages.success(request, 'Logged out')
        return redirect('account_login')
    
    return render(request, 'users/logout.html')


def profiles(request):
    search_query = request.GET.get('search_query') or ''
    
    profiles = Profile.objects.annotate(
        skills_text=Coalesce(
            StringAgg('skills__skill__name', delimiter=' '),
            Value(''),
            output_field=CharField()
        )
    ).order_by('created')

    if search_query:
        vector = SearchVector(
            'display_name',
            'bio',
            'about_info',
            'skills_text'
        )
        query = SearchQuery(search_query)
        search_headline = SearchHeadline('about_info', query)

        profiles = profiles.annotate(rank=SearchRank(vector, query)).annotate(headline=search_headline).filter(rank__gte=0.001).order_by('-rank')
    
    profiles, custom_range, pg = pagination(request, profiles, 6)

    context = {
        'profiles': profiles,
        'search_query': search_query,
        'custom_range': custom_range,
        'pg': pg,
        'search_query': search_query,
    }

    return render(request, 'users/profiles.html', context)


def profile_overview(request, pk):
    profile = get_object_or_404(Profile, id=pk)

    context = {
        'profile': profile,
    }

    return render(request, 'users/profile_overview.html', context)


def profile(request, username):
    profile = get_object_or_404(Profile, user__username=username)
    context = {
        'profile': profile,
        'socials': profile.get_socials,
        'skills': profile.get_skills,
        'page': 'profile',
    }
    return render(request, 'users/profile.html', context)

users/templates/users/account.html
{% extends 'layouts/blank.html' %}

{% block content %}
    
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="profile-card text-center shadow position-relative p-3 radius-md">
                
                <!-- edit profile -->
                <button 
                    type="button" 
                    class="btn position-absolute top-0 end-0 m-3 text-decoration-none text-muted"
                    data-bs-toggle="modal"
                    data-bs-target="#modal"
                    hx-get="{% url 'users:edit_profile' %}"
                    hx-target="#dialog"
                >
                    <i class="fas fa-edit fa-lg"></i>
                </button>

                <div class="profile-info" hx-get="{% url 'users:profile_info' %}" hx-trigger="load, profileInfoChanged from:body">
                </div>

                <div class="socials" hx-get="{% url 'users:social_list' %}" hx-trigger="load, socialListChanged from:body">
                </div>

                <!-- add social -->
                <button
                    type="button"
                    class="btn btn-primary btn-sm radius-md mb-3"
                    data-bs-toggle="modal"
                    data-bs-target="#modal"
                    hx-get="{% url 'users:add_social' %}"
                    hx-target="#dialog"
                >
                    <i class="fas fa-plus"></i> Add social
                </button>
            
                <button class="btn btn-primary radius-md w-100">
                    <i class="fas fa-paper-plane"></i> Send Message
                </button>
            </div>
            
        </div>

        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12 mb-4">
                    <div class="card border-0">
                        <div class="card-body">
                            <h3>About Me</h3>
                            <p>{{ profile.about_info }}</p>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 mb-4">
                    <h3>Skills</h3>

                    <button 
                        type="button" 
                        class="btn btn-primary btn-sm radius-md"
                        data-bs-toggle="modal"
                        data-bs-target="#modal"
                        hx-get="{% url 'users:add_skill' %}"
                        hx-target="#dialog"
                    >
                        <i class="fas fa-plus"></i> Add skill
                    </button>

                    <div class="skills-list mt-2" 
                        hx-get="{% url 'users:skill_list' %}"
                        hx-trigger="load, skillListChanged from:body"
                    >
                        <span>Loading...</span>
                    </div>
                </div>

                <div class="col-md-12 mb-4">
                    <h3>Projects</h3>

                    <button 
                        type="button" 
                        class="btn btn-primary btn-sm radius-md mb-2"
                        data-bs-toggle="modal"
                        data-bs-target="#projectModal"
                        hx-get="{% url 'projects:add_project' %}"
                        hx-target="#projectDialog"
                    >
                        <i class="fas fa-plus"></i> Add project
                    </button>

                    <div class="row"
                        hx-get="{% url 'projects:project_list' %}"
                        hx-trigger="load, projectsChanged from:body"
                    >
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/delete_skill.html
{% block content %}

<form hx-post="{% url 'users:delete_skill' skill.id %}" class="modal-content">
    {% csrf_token %}

    <div class="modal-header">
        <h4>Delete a skill: {{ skill.skill.name }}</h4>
    </div>

    <div class="modal-footer">
        <button class="btn btn-danger radius-md" type="submit">Delete</button>
        <button type="button" class="btn btn-secondary radius-md" data-bs-dismiss="modal">Close</button>
    </div>
    
</form>

{% endblock content %}

users/templates/users/edit_profile.html
{% block content %}

<form 
    hx-post="{% url 'users:edit_profile' %}" 
    class="modal-content radius-md" 
    enctype="multipart/form-data" 
    hx-encoding="multipart/form-data"
    hx-trigger="submit"
>
    {% csrf_token %}

    <div class="modal-header">
        <h4>Edit Profile</h4>
    </div>

    <div class="modal-body">
        {{ form.as_p }}
    </div>

    <div class="modal-footer">
        <button class="btn btn-primary radius-md" type="submit">Save</button>
        <button type="button" class="btn btn-secondary radius-md" data-bs-dismiss="modal">Close</button>
    </div>
    
</form>

{% endblock content %}

users/templates/users/logout.html
{% block content %}
    
<div class="modal-content radius-md">
    <div class="modal-body text-center">
        <div class="modal-header">
            <h4>Are you sure?</h4>
        </div>
        <form method="post" action="{% url 'users:logout' %}" class="d-flex justify-content-center mt-4">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mx-2 radius-md">Log out</button>
            <button type="button" class="btn btn-secondary mx-2 radius-md" data-bs-dismiss="modal">Cancel</button>
        </form>
    </div>
</div>

{% endblock content %}

users/templates/users/obj_delete.html
{% block content %}

<form hx-post="{{ url }}" class="modal-content radius-md">
    {% csrf_token %}

    <div class="modal-header">
        <h4>Delete a {{ obj_name }}: {{ obj_name_value }}</h4>
    </div>

    <div class="modal-body text-center">
        <button class="btn btn-danger radius-md" type="submit">Remove</button>
        <button type="button" class="btn btn-secondary radius-md" data-bs-dismiss="modal">Close</button>
    </div>
    
</form>

{% endblock content %}

users/templates/users/obj_form.html
{% block content %}

<form hx-post="{{ url }}" class="modal-content radius-md shadow-lg p-4 border-0">
    {% csrf_token %}

    <div class="modal-header border-0">
        <h4 class="modal-title fw-bold text-primary">Add {{ obj_name }}</h4>
    </div>

    <div class="modal-body text-center">
        {{ form.as_p }}
    </div>

    <div class="modal-footer border-0 d-flex justify-content-center">
        <button class="btn btn-primary radius-md px-4" type="submit">
            <i class="fas fa-plus"></i> Add
        </button>
        <button type="button" class="btn btn-secondary radius-md px-4" data-bs-dismiss="modal">
            <i class="fas fa-times"></i> Close
        </button>
    </div>
    
</form>

{% endblock content %}

users/templates/users/obj_options.html
{% for obj in queryset %}
    <option value="{{ obj.id }}">{{ obj.name }}</option>
{% endfor %}

users/templates/users/profile_overview.html
{% block content %}

<div class="modal-content radius-md">
    <div class="modal-header">
        <h5 class="modal-title" id="profileOverviewModalLabel">Profile Overview</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <div class="modal-body">
        <div class="d-flex align-items-center mb-3">
            <img src="{{ profile.image.url }}" alt="Profile Picture" class="rounded-circle" width="80" height="80">
            <div class="ms-3 d-flex flex-column justify-content-center">
                <h5 class="mb-0">{{ profile.get_name }}</h5>
                <small class="text-muted">@{{ profile.get_username }}</small>
                <p class="text-muted mb-0">{{ profile.get_bio }}</p>
            </div>
        </div>
        
        <div class="social-icons mb-3 d-flex flex-wrap justify-content-center gap-3">
            {% for social in profile.get_socials %}
                <div class="d-flex flex-wrap justify-content-center gap-1">
                    <a href="{{ social.url }}"><i class="fab fa-{{ social.name }} fa-lg"></i></a>
                </div>
            {% endfor %}
        </div>

        {% if profile.about_info %}
            <p>
                {{ profile.about_info|slice:200 }}...
            </p>
        {% endif %}

        <div class="tags mb-3">
            {% if profile.get_skills %}
                {% for skill in profile.get_skills %}
                    <a href="" class="tag text-decoration-none radius-md mt-1">#{{ skill.name }}</a>
                {% endfor %}
            {% else %}
                <small class="text-muted">No skills yet</small>
            {% endif %}
        </div>
    </div>

    <div class="modal-footer">
        <a href="{% url 'users:profile' profile.get_username %}" class="btn btn-primary radius-md">View Full Profile</a>
        <button type="button" class="btn btn-secondary radius-md" data-bs-dismiss="modal">Close</button>
    </div>
</div>

{% endblock content %}

users/templates/users/profiles.html
{% extends 'layouts/blank.html' %}

{% block content %}

<div class="container mt-5">
    <div class="mb-4 text-center">
        <h2>Developers</h2>
        {% if search_query %}
            <span>Results: {{ profiles|length }}</span>
        {% endif %}
    </div>

    <div class="row">
        
        {% for profile in profiles %}

            <div class="col-md-4 mb-4">
                <div class="card shadow p-3 radius-md border-0"
                {% if request.user.profile == profile %}
                    style="border: 5px solid rgb(0, 189, 0) !important"
                {% endif %}
                >
                {% if request.user.profile == profile %}
                <span class="position-absolute text-white top-0 end-0 m-3 text-sm bg-cyan radius-md p-1">
                    Your profile
                </span>
                {% endif %}
                    <div class="d-flex align-items-center">
                        <img src="{{ profile.image.url }}" alt="Profile Picture" class="profile-img">
                        <div class="ms-3">
                            <h5 class="mb-1">{{ profile.get_name }}</h5>
                            <p class="text-muted mb-0">{{ profile.get_bio }}</p>
                        </div>
                    </div>
                    <p class="profile-description mt-3 mb-2">
                        {% if profile.about_info %}
                            {{ profile.about_info|slice:50 }}...
                        {% else %}
                            No description yet.
                        {% endif %}
                    </p>
                    
                    <div class="mb-3">
                        {% for skill in profile.get_skills|slice:3 %}
                            <a href="" class="tag text-decoration-none radius-md">#{{ skill.name }}</a>
                        {% endfor %}
                        {% if profile.get_skills.count and profile.get_skills.count > 3 %}
                            <small style="color: rgb(144, 189, 202);">and more...</small>
                        {% endif %}
                    </div>

                    <div class="d-flex flex-column flex-sm-row gap-2">
                        <a href="{% url 'users:profile' profile.get_username %}" class="btn btn-primary btn-sm radius-md w-100 w-sm-50">
                            <i class="fas fa-user me-1"></i> View Profile
                        </a>
                    
                        <button
                            class="btn btn-info btn-sm radius-md w-100 w-sm-50"
                            type="button"
                            data-bs-toggle="modal"
                            data-bs-target="#modal"
                            hx-get="{% url 'users:profile_overview' profile.id %}"
                            hx-target="#dialog"
                        >
                            <i class="fas fa-search me-1"></i> Quick overview
                        </button>
                    </div>
                    
                    
                </div>
            </div>

        {% endfor %}

    </div>

    {% include 'includes/pagination.html' with queryset=profiles %}

</div>

{% endblock content %}

users/templates/users/skill_form.html
{% block content %}

<form hx-post="{% url 'users:add_skill' %}" class="modal-content">
    {% csrf_token %}

    <div class="modal-header">
        <h4>Add Skill</h4>
    </div>

    <div class="modal-body">
        {{ form.as_p }}
    </div>

    <div class="modal-footer">
        <button class="btn btn-primary radius-md" type="submit">Add</button>
        <button type="button" class="btn btn-secondary radius-md" data-bs-dismiss="modal">Close</button>
    </div>
    
</form>

{% endblock content %}